spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parkkbus
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

security:
  jwt:
    secret: my-super-secret-key-my-super-secret-key
    expiration: 3600000