apiVersion: v1
kind: Secret
metadata:
  name: parkkbus-secret
  namespace: parkkbus
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "changeme"
  JWT_SECRET: "change-this-jwt-secret-in-production"

